### ISSUE TITLE
Save doesn't complete.

### ISSUE THREAD

**Issue by Zelphin67** [Cibola8/cibola8#1]
Only removed background to an image on a character. Then selected save. Save kept spinning for over 5 minutes. Finally gave up.

![image](https://github.com/user-attachments/assets/8d025acb-1592-4345-bc8c-38dc225edbca)

**Comment by Zelphin67** [comment]
REmoved all modules except Cibola. Still did the same thing.

**Comment by Zelphin67** [comment]
THis was updating a character portrait in DnD 4.0.3 game system. I have been able to modify tiles and save them and that worked. I've tried multiple times for character portraits in many different ways but saving hasn't worked yet.

**Comment by Cibola8** [comment]
Thanks for reporting. Could you please open the console with (F12 on windows) then go to console tab.
Afterwards click on save and check if there appears any error in red.
If so please post it here

This is how the console looks in e.g. Firefox
![grafik](https://github.com/user-attachments/assets/fc6a1ee5-930b-4ab3-8421-53185ee50568)

Do you have the newest cibola 8 module installed 1.7.1?

**Comment by Cibola8** [comment]
Ah I see, I think I know why it fails. Will bring a fix today

**Comment by Zelphin67** [comment]
Just tried out new version and it worked. Great!
